language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jaab30/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jaab30/react-test npm run test

after_success:
  - docker build -t jaab30/multi-client ./client
  - docker build -t jaab30/multi-nginx ./nginx
  - docker build -t jaab30/multi-server ./server
  - docker build -t jaab30/multi-worker ./worker
  # Logh to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push jaab30/multi-client 
  - docker push jaab30/multi-nginx 
  - docker push jaab30/multi-server 
  - docker push jaab30/multi-worker 